instance_destroy(ClickableMusicLess1)
instance_destroy(ClickableMusicPlus1)
instance_destroy(ClickableSpeed1)
instance_destroy(ClickableSpeed2)
instance_destroy(ClickableSpeed3)
instance_destroy(ClickableSpeed4)
instance_destroy(BOpts_SelectBg)
instance_destroy(BOpts_SelectG)
instance_destroy(BoptsClickableCloseWind)
instance_destroy(vehsel_0)



global.spdboost = global.levelspeed